# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does - deploy app to carshlytics with commit messages of commits between last build release and current build release between last and invite testers for app testing"
  
lane :beta do
  
  File.open('hashfile','r') do |file|
  oldHash = file.read()
  
  commit = last_git_commit
  hash = commit[:commit_hash]
  
  commitMessages = changelog_from_git_commits(
   between: [oldHash,hash])

  File.open('hashfile','w') do |file|
  file.write(hash)

  build_app(scheme: "Employees World",
            project: "Employees World.xcodeproj",
            output_directory: "/Users/waseemwani/Desktop/Employees World",
	    clean: true,        
            export_method: "development",
            include_bitcode: true)
crashlytics(api_token:"0a83081cf9414a0fd0ffec5772b880a9dc007953",build_secret:"3a605ea7788c9a352965f849572fa95a2bbdcda8cf6697427c85acdbe48689b6", notes: commitMessages,emails: "waseem.ahmed@tothenew.com, ankit.nigam@tothenew.com")
end
end
end

end