# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  
lane :beta do
  commit = last_git_commit
  build_app(scheme: "Employees World",
            project: "Employees World.xcodeproj",
            output_directory: "/Users/waseemwani/Desktop/Employees World",
	    clean: true,        
            export_method: "development",
            include_bitcode: true)
slack(message: “Application was built and successfully uploaded to crashlytics”)
crashlytics(api_token:"0a83081cf9414a0fd0ffec5772b880a9dc007953",build_secret:"3a605ea7788c9a352965f849572fa95a2bbdcda8cf6697427c85acdbe48689b6", notes: commit[:message],emails: "waseem.ahmed@tothenew.com, ankit.nigam@tothenew.com")
end

lane :lastcommit do
commit = last_git_commit
author = commit[:author]
author_email = commit[:author_email]
end

lane :gitclean do
ensure_git_status_clean
end

lane :printOut do
commit = number_of_commits
puts commit
end
end